### ISSUE TITLE
wrong for install

### ISSUE THREAD

**Issue by jhive-cn** [he1per/psmouse-dkms-alpsv7#24]
Building module:
cleaning build area...
make -j4 KERNELRELEASE=4.8.13-1-ARCH -C /usr/lib/modules/4.8.13-1-ARCH/build M=/var/lib/dkms/psmouse-dkms-alpsv7/1.1/build/src psmouse.ko...(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.8.13-1-ARCH (x86_64)
Consult /var/lib/dkms/psmouse-dkms-alpsv7/1.1/build/make.log for more information.
▶▶▶▶ Error: Build failed

**Comment by van9petryk** [comment]
Same propblem:

ivan@ivan-Latitude-E5530-non-vPro:/tmp/psmouse-dkms-alpsv7$ sudo ./install.sh
./install.sh: line 16: [: missing `]'
────── Building with dkms ───────


Creating symlink /var/lib/dkms/psmouse-dkms-alpsv7/1.1/source ->
                 /usr/src/psmouse-dkms-alpsv7-1.1

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=4.15.0-23-generic -C /lib/modules/4.15.0-23-generic/build M=/var/lib/dkms/psmouse-dkms-alpsv7/1.1/build/src psmouse.ko...(bad exit status: 2)
ERROR (dkms apport): binary package for psmouse-dkms-alpsv7: 1.1 not found
Error! Bad return status for module build on kernel: 4.15.0-23-generic (x86_64)
Consult /var/lib/dkms/psmouse-dkms-alpsv7/1.1/build/make.log for more information.
▶▶▶▶ Error: Build failed

**Comment by van9petryk** [comment]
ivan@ivan-Latitude-E5530-non-vPro:/var/lib/dkms/psmouse-dkms-alpsv7/1.1/build$ cat make.log
DKMS make.log for psmouse-dkms-alpsv7-1.1 for kernel 4.15.0-23-generic (x86_64)
Tue Jun 19 19:59:26 CEST 2018
make: Entering directory '/usr/src/linux-headers-4.15.0-23-generic'
  CC [M]  /var/lib/dkms/psmouse-dkms-alpsv7/1.1/build/src/psmouse-base.o
  CC [M]  /var/lib/dkms/psmouse-dkms-alpsv7/1.1/build/src/synaptics.o
  CC [M]  /var/lib/dkms/psmouse-dkms-alpsv7/1.1/build/src/alps.o
  CC [M]  /var/lib/dkms/psmouse-dkms-alpsv7/1.1/build/src/elantech.o
/var/lib/dkms/psmouse-dkms-alpsv7/1.1/build/src/alps.c: In function ‘alps_init’:
/var/lib/dkms/psmouse-dkms-alpsv7/1.1/build/src/alps.c:2648:2: error: implicit declaration of function ‘setup_timer’; did you mean ‘setup_irq’? [-Werror=implicit-function-declaration]
  setup_timer(&priv->timer, alps_flush_packet, (unsigned long)psmouse);
  ^~~~~~~~~~~
  setup_irq
  CC [M]  /var/lib/dkms/psmouse-dkms-alpsv7/1.1/build/src/logips2pp.o
  CC [M]  /var/lib/dkms/psmouse-dkms-alpsv7/1.1/build/src/lifebook.o
  CC [M]  /var/lib/dkms/psmouse-dkms-alpsv7/1.1/build/src/sentelic.o
cc1: some warnings being treated as errors
scripts/Makefile.build:332: recipe for target '/var/lib/dkms/psmouse-dkms-alpsv7/1.1/build/src/alps.o' failed
make[1]: *** [/var/lib/dkms/psmouse-dkms-alpsv7/1.1/build/src/alps.o] Error 1
make[1]: *** Waiting for unfinished jobs....
Makefile:1728: recipe for target 'psmouse.ko' failed
make: *** [psmouse.ko] Error 2
make: Leaving directory '/usr/src/linux-headers-4.15.0-23-generic'
